[build]
  command = "npm run build:netlify"

[build.environment]
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_CLIENT_ENGINE_TYPE = "library"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuração para evitar cache do Prisma
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate" 